title: Supatta Viriyavisuthisakul
logo: asset/image/supatta_circle.jpg
description: 
  King Mongkut's University of Technology Thonburi
  supatta.viri@kmutt.ac.th
email: supatta.viri@kmutt.ac.th
theme: jekyll-theme-minimal
