title: Supatta Viriyavisuthisakul
logo: asset/image/supatta_circle.jpg
description: Department of Mathmetics, Faculty of Science, King.... supatta.viri@kmutt.ac.th
email: supatta.viri@kmutt.ac.th
theme: jekyll-theme-minimal
