title: About me
logo: asset/image/supatta_circle.jpg
description: Department of Mathematics, Faculty of Science, King Mongkut's University of Technology Thonburi, supatta.viri@kmutt.ac.th <br><br> <b>[ <a href="#education">Education</a> ]</b> &nbsp;&nbsp; <b>[ <a href="#news">News</a> ]</b> &nbsp;&nbsp; <br><b>[ <a href="#publications">Publications</a> ]</b><b>[ <a href="#honors">Honors & Awards</a> ]</b>
email: supatta.viri@kmutt.ac.th
email: supatta.viri@kmutt.ac.th
theme: jekyll-theme-minimal

<a id="honors">Honors & Awards</a>
